version: '3'
services:
    grafana:
        container_name: grafana
        image: grafana/grafana
        ports:
            - '3000:3000'
        volumes:
            - grafana-storage:/var/lib/grafana
        links:
            - influxdb
        restart: always
    influxdb:
        container_name: influxdb
        image: influxdb
        ports:
            - "8083:8083"
            - "8086:8086"
        volumes:
            - influxdb-storage:/var/lib/influxdb
        restart: always
    telegraf:
        container_name: telegraf
        image: telegraf
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${PWD}/conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
            - /opt/vc:/opt/vc:ro
        devices:
            - "/dev/vchiq"
        environment:
            LD_LIBRARY_PATH: "/opt/vc/lib"
        network_mode: host
        restart: always
volumes:
    influxdb-storage:
    grafana-storage:
